spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8

server:
  port: 8082
  servlet:
    context-path: /distributionLock